import { PrismaClient, ProductCategory, StockStatus } from "@prisma/client";
import bcrypt from "bcryptjs";
import fs from "fs";
import path from "path";

const prisma = new PrismaClient();

const manifestPath = path.join(process.cwd(), "public", "images", "products", "manifest.json");
const manifest: Record<string, string[]> = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

function imgs(slug: string): string[] {
  const list = manifest[slug];
  if (!list?.length) throw new Error(`Görsel yok: ${slug}`);
  return list;
}

const products = [
  {
    name: "Masa Lambası 1406",
    slug: "masa-lambasi-1406",
    shortDescription: "Minimal formlu, çağdaş tasarım masa lambası.",
    description:
      "Sade silüetiyle çalışma masası, komodin veya konsol üzerinde soft ambient ışık sunar.\n\n**Not:** Sipariş talebi sonrası stok ve teslimat teyit edilir.",
    price: 18500,
    category: ProductCategory.AYDINLATMA,
    material: "Metal / cam",
    dimensions: "Ürün kartına göre",
    colors: ["Siyah", "Metalik"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "2–4 hafta",
    images: imgs("masa-lambasi-1406"),
    featured: true,
    sortOrder: 1,
    projectNote: "Okuma köşesi ve yatak odası komodinleri için önerilir.",
  },
  {
    name: "Anita Emperador Masa Lambası",
    slug: "anita-emperador-masa-lambasi",
    shortDescription: "Emperador mermer gövdeli, Lorenza Bozzoli imzalı masa lambası.",
    description:
      "Doğal Emperador mermer ile heykelsi bir aydınlatma parçası. Lüks oturma ve yatak odalarına karakter katar.\n\n**Bakım:** Mermer yüzeyi yumuşak nemli bezle silin.",
    price: 42000,
    category: ProductCategory.AYDINLATMA,
    material: "Emperador mermer",
    dimensions: "Ürün kartına göre",
    colors: ["Emperador Kahve"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–5 hafta",
    images: imgs("anita-emperador-masa-lambasi"),
    featured: true,
    sortOrder: 2,
    projectNote: "Salon konsolu veya yatak odası şifonyer üzerinde odak parçası.",
  },
  {
    name: "Pluma Alabaster Masa Lambası",
    slug: "pluma-alabaster-masa-lambasi",
    shortDescription: "Alabaster difüzörlü, yumuşak ışık yayan masa lambası.",
    description:
      "Alabaster gövde ışığı yumuşatarak mekâna sıcak bir ambient katman ekler.\n\n**Ampul:** LED önerilir.",
    price: 26800,
    category: ProductCategory.AYDINLATMA,
    material: "Alabaster",
    dimensions: "Ürün kartına göre",
    colors: ["Doğal Alabaster"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–5 hafta",
    images: imgs("pluma-alabaster-masa-lambasi"),
    featured: true,
    sortOrder: 3,
    projectNote: "Gece aydınlatması ve lounge alanları için uygundur.",
  },
  {
    name: "Ginevra Daybed",
    slug: "ginevra-daybed",
    shortDescription: "Zarif formlu daybed — dinlenme ve oturma alanları için.",
    description:
      "Klasik çizgilerle çağdaş konforu birleştiren daybed. Salon, yatak odası veya giyinme odasında kullanılır.\n\n**Not:** Kumaş / kaplama seçenekleri talep üzerine netleştirilir.",
    price: 17700,
    category: ProductCategory.MOBILYA,
    material: "Ahşap iskelet, döşeme",
    dimensions: "Ürün kartına göre",
    colors: ["Kumaş seçenekli"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "6–10 hafta",
    images: imgs("ginevra-daybed"),
    featured: true,
    sortOrder: 4,
    projectNote: "Geniş salon ve master suite projelerinde imza parçası.",
  },
  {
    name: "Louis XV Daybed",
    slug: "louis-xv-daybed",
    shortDescription: "Louis XV stilinde klasik daybed.",
    description:
      "Tarihsel referanslı, oyma detaylı daybed. Klasik ve eklektik mekânlara uyum sağlar.",
    price: 33030,
    category: ProductCategory.MOBILYA,
    material: "Ahşap, döşeme",
    dimensions: "Ürün kartına göre",
    colors: ["Kumaş seçenekli"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "6–10 hafta",
    images: imgs("louis-xv-daybed"),
    featured: false,
    sortOrder: 5,
    projectNote: "Klasik villa ve butik otel odaları için önerilir.",
  },
  {
    name: "Brooklyn Bouclé Pouf",
    slug: "brooklyn-boucle-pouf",
    shortDescription: "Siyah-beyaz bouclé ve deri kemer detaylı pouf.",
    description:
      "Dokulu bouclé yüzey ve siyah deri kemer detayıyla oturma grubunu tamamlayan pouf.",
    price: 4880,
    category: ProductCategory.MOBILYA,
    material: "Bouclé kumaş, deri detay",
    dimensions: "Ürün kartına göre",
    colors: ["Siyah", "Beyaz"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "4–6 hafta",
    images: imgs("brooklyn-boucle-pouf"),
    featured: true,
    sortOrder: 6,
    projectNote: "Modern salonlarda ek oturma ve footrest olarak kullanılır.",
  },
  {
    name: "Nefelibata Pouf",
    slug: "nefelibata-pouf",
    shortDescription: "Stormo Studio imzalı, tekil tasarım pouf.",
    description:
      "Benzersiz form diliyle mekânda sanat objesi gibi duran pouf. Koleksiyon parçası niteliğindedir.",
    price: 3600,
    category: ProductCategory.MOBILYA,
    material: "Döşeme / tekstil",
    dimensions: "Ürün kartına göre",
    colors: ["Doğal tonlar"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "5–8 hafta",
    images: imgs("nefelibata-pouf"),
    featured: true,
    sortOrder: 7,
    projectNote: "Lounge ve gallery-benzeri yaşam alanları için.",
  },
  {
    name: "Lloyd Siyah Yüksek Pouf",
    slug: "lloyd-siyah-yuksek-pouf",
    shortDescription: "Siyah ahşap detaylı yüksek pouf.",
    description: "Kompakt, yüksek formlu pouf. Bar, mutfak adası veya oturma grubu yanına uygundur.",
    price: 3415,
    category: ProductCategory.MOBILYA,
    material: "Ahşap, döşeme",
    dimensions: "Ürün kartına göre",
    colors: ["Siyah"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "4–6 hafta",
    images: imgs("lloyd-siyah-yuksek-pouf"),
    featured: false,
    sortOrder: 8,
    projectNote: null,
  },
  {
    name: "Patapouff Ottoman",
    slug: "patapouff-ottoman",
    shortDescription: "Yumuşak formlu, rahat oturma sunan ottoman.",
    description: "Organik silüetli ottoman; footrest veya ek oturma olarak kullanılır.",
    price: 2190,
    category: ProductCategory.MOBILYA,
    material: "Döşeme",
    dimensions: "Ürün kartına göre",
    colors: ["Kumaş seçenekli"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "4–6 hafta",
    images: imgs("patapouff-ottoman"),
    featured: false,
    sortOrder: 9,
    projectNote: null,
  },
  {
    name: "Milady Timsah Baskı Sandalye",
    slug: "milady-timsah-sandalye",
    shortDescription: "Siyah timsah baskı deri katlanır sandalye.",
    description:
      "Güçlü karakterli, katlanabilir sandalye. Yemek alanı, yatak odası veya staging için çarpıcı bir parça.",
    price: 1590,
    category: ProductCategory.MOBILYA,
    material: "Baskılı deri",
    dimensions: "Ürün kartına göre",
    colors: ["Siyah"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "5–8 hafta",
    images: imgs("milady-timsah-sandalye"),
    featured: true,
    sortOrder: 10,
    projectNote: "Statement sandalye olarak tekil kullanım önerilir.",
  },
  {
    name: "Happy Velvet Dikdörtgen Kırlent",
    slug: "happy-velvet-dikdortgen-kirlent",
    shortDescription: "Tuğla kırmızısı ve beyaz kadife dikdörtgen kırlent.",
    description: "Kontrast renkli velvet kırlent; koltuk ve daybed styling’inde canlılık katar.",
    price: 4200,
    category: ProductCategory.TEKSTIL,
    material: "Velvet",
    dimensions: "Dikdörtgen",
    colors: ["Tuğla Kırmızı", "Beyaz"],
    stockStatus: StockStatus.IN_STOCK,
    deliveryTime: "2–4 hafta",
    images: imgs("happy-velvet-dikdortgen-kirlent"),
    featured: false,
    sortOrder: 11,
    projectNote: null,
  },
  {
    name: "Happy Frame Deve Tüyü Kırlent",
    slug: "happy-frame-deve-tuyu-kirlent",
    shortDescription: "Deve tüyü tonunda kare velvet kırlent.",
    description: "Sıcak nötr tonlarda kare kırlent; oturma grubunu tamamlar.",
    price: 3800,
    category: ProductCategory.TEKSTIL,
    material: "Velvet",
    dimensions: "Kare",
    colors: ["Deve Tüyü"],
    stockStatus: StockStatus.IN_STOCK,
    deliveryTime: "2–4 hafta",
    images: imgs("happy-frame-deve-tuyu-kirlent"),
    featured: false,
    sortOrder: 12,
    projectNote: null,
  },
  {
    name: "The Gift Hardal Mini Kırlent (2'li)",
    slug: "the-gift-hardal-mini-kirlent",
    shortDescription: "Saçaklı hardal kadife mikro kırlent seti (2 adet).",
    description: "Küçük ölçekli, saçak detaylı hardal velvet kırlent çifti.",
    price: 5200,
    category: ProductCategory.TEKSTIL,
    material: "Velvet",
    dimensions: "Mikro / set 2’li",
    colors: ["Hardal"],
    stockStatus: StockStatus.IN_STOCK,
    deliveryTime: "2–4 hafta",
    images: imgs("the-gift-hardal-mini-kirlent"),
    featured: true,
    sortOrder: 13,
    projectNote: "Katmanlı styling için ideal.",
  },
  {
    name: "Viburno Desenli Kırlent",
    slug: "viburno-desenli-kirlent",
    shortDescription: "Mavi ve bej desenli dikdörtgen kırlent.",
    description: "Desenli tekstil kırlent; klasik ve modern mekânlarda denge kurar.",
    price: 4500,
    category: ProductCategory.TEKSTIL,
    material: "Dokuma tekstil",
    dimensions: "Dikdörtgen",
    colors: ["Mavi", "Bej"],
    stockStatus: StockStatus.IN_STOCK,
    deliveryTime: "2–4 hafta",
    images: imgs("viburno-desenli-kirlent"),
    featured: false,
    sortOrder: 14,
    projectNote: null,
  },
  {
    name: "Abito C Fossena Vazo",
    slug: "abito-c-fossena-vazo",
    shortDescription: "Heykelsi formlu Fossena vazo.",
    description: "Konsol ve sehpa üzerinde odak noktası oluşturan dekoratif vazo.",
    price: 9800,
    category: ProductCategory.OBJE,
    material: "Seramik / cam",
    dimensions: "Ürün kartına göre",
    colors: ["Doğal"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–5 hafta",
    images: imgs("abito-c-fossena-vazo"),
    featured: false,
    sortOrder: 15,
    projectNote: null,
  },
  {
    name: "Ballarina Murano Cam Kase",
    slug: "ballarina-murano-cam-kase",
    shortDescription: "Altın ve pembe mermer efektli Murano cam kase.",
    description: "Murano cam işçiliğiyle üretilmiş heykelsi kase / centerpiece.",
    price: 22000,
    category: ProductCategory.OBJE,
    material: "Murano cam",
    dimensions: "Ürün kartına göre",
    colors: ["Altın", "Pembe"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–6 hafta",
    images: imgs("ballarina-murano-cam-kase"),
    featured: true,
    sortOrder: 16,
    projectNote: "Yemek masası ve konsol styling’i için.",
  },
  {
    name: "Karkade Murano Cam Vazo",
    slug: "karkade-murano-vazo",
    shortDescription: "Bucket formlu Murano cam vazo.",
    description: "Canlı renkli Murano cam vazo; modern salonlara enerji katar.",
    price: 16500,
    category: ProductCategory.OBJE,
    material: "Murano cam",
    dimensions: "Ürün kartına göre",
    colors: ["Kırmızı / pembe tonlar"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–6 hafta",
    images: imgs("karkade-murano-vazo"),
    featured: false,
    sortOrder: 17,
    projectNote: null,
  },
  {
    name: "Pembe Murano Cam Vazo",
    slug: "pembe-murano-vazo",
    shortDescription: "Pembe tonlarda bucket Murano cam vazo.",
    description: "Yumuşak pembe Murano cam vazo; çiçek veya tek başına obje olarak kullanılır.",
    price: 15800,
    category: ProductCategory.OBJE,
    material: "Murano cam",
    dimensions: "Ürün kartına göre",
    colors: ["Pembe"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–6 hafta",
    images: imgs("pembe-murano-vazo"),
    featured: false,
    sortOrder: 18,
    projectNote: null,
  },
  {
    name: "Siyah Uzun Form Vazo",
    slug: "siyah-uzun-form-vazo",
    shortDescription: "Siyah, uzun silüetli dekoratif vazo.",
    description: "Minimal siyah vazo; modern mekânlarda dikey vurgu yaratır.",
    price: 7200,
    category: ProductCategory.OBJE,
    material: "Seramik",
    dimensions: "Ürün kartına göre",
    colors: ["Siyah"],
    stockStatus: StockStatus.IN_STOCK,
    deliveryTime: "2–4 hafta",
    images: imgs("siyah-uzun-form-vazo"),
    featured: false,
    sortOrder: 19,
    projectNote: null,
  },
  {
    name: "Eden Sicilya Maiolica Heykel",
    slug: "eden-sicilya-maiolica",
    shortDescription: "Sicilya maiolica dekoratif heykel.",
    description: "El boyaması maiolica geleneğinden ilham alan dekoratif heykel.",
    price: 18500,
    category: ProductCategory.OBJE,
    material: "Maiolica seramik",
    dimensions: "Yaklaşık 26 cm",
    colors: ["Renkli"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–5 hafta",
    images: imgs("eden-sicilya-maiolica"),
    featured: false,
    sortOrder: 20,
    projectNote: null,
  },
  {
    name: "Masini Safari Yumurta Heykel",
    slug: "masini-safari-yumurta",
    shortDescription: "Safari koleksiyonundan koleksiyonluk yumurta heykeli.",
    description: "Dekoratif collectible heykel; vitrin ve konsol için.",
    price: 11200,
    category: ProductCategory.OBJE,
    material: "Seramik / reçine",
    dimensions: "Ürün kartına göre",
    colors: ["Safari tonları"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–5 hafta",
    images: imgs("masini-safari-yumurta"),
    featured: false,
    sortOrder: 21,
    projectNote: null,
  },
  {
    name: "Morandi N.3 Mor Dekoratif Şişe",
    slug: "morandi-n3-mor-sise",
    shortDescription: "Morandi esintili mor dekoratif şişe.",
    description: "Sakin mor tonda dekoratif şişe; gruplama veya tekil vurgu için.",
    price: 6400,
    category: ProductCategory.OBJE,
    material: "Cam / seramik",
    dimensions: "Ürün kartına göre",
    colors: ["Mor"],
    stockStatus: StockStatus.IN_STOCK,
    deliveryTime: "2–4 hafta",
    images: imgs("morandi-n3-mor-sise"),
    featured: false,
    sortOrder: 22,
    projectNote: null,
  },
  {
    name: "Nina Gri Reçine Centerpiece",
    slug: "nina-gri-centerpiece",
    shortDescription: "Gri reçine centerpiece / merkez obje.",
    description: "Yemek masası veya konsol için modern centerpiece.",
    price: 8900,
    category: ProductCategory.OBJE,
    material: "Reçine",
    dimensions: "Ürün kartına göre",
    colors: ["Gri"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–5 hafta",
    images: imgs("nina-gri-centerpiece"),
    featured: false,
    sortOrder: 23,
    projectNote: null,
  },
  {
    name: "Vase For Two #4 Gri Seramik",
    slug: "vase-for-two-4-gri",
    shortDescription: "Gri seramik çift formlu vazo.",
    description: "Çift gövdeli gri seramik vazo; minimal mekânlara uygundur.",
    price: 7800,
    category: ProductCategory.OBJE,
    material: "Seramik",
    dimensions: "Ürün kartına göre",
    colors: ["Gri"],
    stockStatus: StockStatus.MADE_TO_ORDER,
    deliveryTime: "3–5 hafta",
    images: imgs("vase-for-two-4-gri"),
    featured: false,
    sortOrder: 24,
    projectNote: null,
  },
];

async function main() {
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.admin.deleteMany();
  await prisma.contactMessage.deleteMany();
  await prisma.siteSettings.deleteMany();

  const passwordHash = await bcrypt.hash("BarisOker2026!", 12);

  await prisma.admin.create({
    data: {
      email: "admin@barisoker.com",
      passwordHash,
      name: "Barış Öker Admin",
    },
  });

  await prisma.siteSettings.create({
    data: {
      id: "default",
      shippingFee: 150,
      freeShippingMinimum: 5000,
      phone: "+90 506 584 73 51",
      email: "barsokrr@gmail.com",
      whatsapp: "905065847351",
      instagram: "barisoker.studio",
      city: "İstanbul",
      shippingNote:
        "5.000 ₺ ve üzeri siparişlerde kargo ücretsizdir. Altındaki siparişlerde 150 ₺ kargo ücreti uygulanır.",
    },
  });

  for (const product of products) {
    await prisma.product.create({
      data: {
        ...product,
        colors: JSON.stringify(product.colors),
        images: JSON.stringify(product.images),
        active: true,
      },
    });
  }

  console.log(`Seed tamamlandı: ${products.length} ürün, admin ve site ayarları oluşturuldu.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
